### ISSUE TITLE
Use of the word "tag", verb and noun

### ISSUE THREAD

**Issue by laurencelundblade** [cabo/cbor-oid#11]
My understanding is that in CBOR a "tag" is the construct of both the tag number and the tag content. A tag number by itself is not a tag. That implies the verb to "tag" is not the adding of a tag number. It seems some sentences in section 4 should be reworded.

> OID tags can tag byte strings 

Would be better as "the content of an OID tag can be a byte string"

> When an OID tag is applied to an array

Would be better as "When the content of an OID tag is an array"

> For example, when an array is tagged with TBD111

Would be better as "For example, when the tag content is an array and the tag number is TBD111"

There is use of the word "tag" and "tags" in section 2 that could be improved in this way too.

(I'm bringing this up, because this was a major point of confusion for me about the nature of tags and because there was a conversation from some time ago involving Jim Schaad and others that I think came to the conclusion that a CBOR tag is not just the tag number, but construction of the number and the content).

**Comment by cabo** [comment]
Instead of making a large number of sentences harder to read, I resorted to an intro in the definitions (which essentially indicates the way the verb "to tag" is used in 8949).  But there indeed were a few places that didn't need to be made more complex, and I changed those.  Please see and review PR #12!

**Comment by cabo** [comment]
Addressed by #12 (submitted as -08).
