### ISSUE TITLE
Add a tag specifically for PENs (OIDs relative to 1.3.6.1.4.1)

### ISSUE THREAD

**Issue by cabo** [cabo/cbor-oid#7]
As per <https://mailarchive.ietf.org/arch/msg/cbor/KkpeLxkeW69do_W-nb-wB6ufaXs>

**Comment by mcr** [comment]
"This means that we should probably maintain X.690 Clause 8.20 semantics in the body."  please write this explicitely into the text ÷)

**Comment by cabo** [comment]
What does that mean then?

**Comment by mcr** [comment]
> What does that mean then?

I want you to restate/paraphrase/quote the meaning from 8.20.
I now have access to X.690, a few years ago, they were hidden been deep paywalls.  Some people reading our documents might not be able to reach that document.  I think the point is that the binary stuff that follows is *not* a CBOR integer, but a BER encoded integer with all the 0x80 magic.

**Comment by cabo** [comment]
I believe all that content is already covered in draft-ietf-cbor-tags-oid.  So by saying that tag 112 is like 110, but understood to be anchored at 1.3.6.1.4.1, should do it.
